# Generated by Django 5.1.3 on 2025-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image_prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
