# Generated by Django 5.1.3 on 2024-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialmedia_rename_code_country_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
