# Generated by Django 5.1.3 on 2024-12-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_country_code_alter_country_currency_and_more'),
        ('shelters', '0008_remove_shelter_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
