# Generated by Django 5.1.3 on 2024-12-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
