# Generated by Django 5.1.3 on 2025-03-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vārds')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID')),
                ('behavior', models.IntegerField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], null=True, verbose_name='Uzvedība')),
                ('size', models.IntegerField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], null=True, verbose_name='Izmērs')),
                ('age', models.IntegerField(blank=True, choices=[(1, 'Mazulis'), (2, 'Pieaugušais'), (3, 'Seniors')], null=True, verbose_name='Vecums')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], null=True, verbose_name='Dzimums')),
                ('species', models.IntegerField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], verbose_name='Suga')),
                ('pattern', models.IntegerField(blank=True, choices=[(1, 'Vienkrāsains'), (2, 'Strīpains'), (3, 'Punktveida'), (4, 'Plankumains'), (5, 'Raibs')], null=True, verbose_name='Kažoka raksts')),
                ('primary_color', models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Pamatkrāsa')),
                ('secondary_color', models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Sekundārā krāsa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Piezīmes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact_phone', models.IntegerField(blank=True, null=True, verbose_name='Kontakttālrunis')),
                ('phone_code', models.IntegerField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], null=True, verbose_name='Telefona kods')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sķirne')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Attēls')),
                ('extra_image_1', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 1.')),
                ('extra_image_2', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 2.')),
                ('extra_image_3', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 3.')),
                ('extra_image_4', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 4.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mājdzīvnieks',
                'verbose_name_plural': 'Mājdzīvnieki',
            },
        ),
        migrations.CreateModel(
            name='PetSightingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sightnings_images/', verbose_name='Attēls')),
                ('status', models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], verbose_name='Statuss')),
                ('event_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='Notikuma laiks')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings_history', to='pets.pet')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
