# Generated by Django 5.1.3 on 2025-04-16 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vārds')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID')),
                ('behavior', models.IntegerField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], null=True, verbose_name='Uzvedība')),
                ('size', models.IntegerField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], null=True, verbose_name='Izmērs')),
                ('age', models.IntegerField(blank=True, choices=[(1, 'Mazulis'), (2, 'Pieaugušais'), (3, 'Seniors')], null=True, verbose_name='Vecums')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], null=True, verbose_name='Dzimums')),
                ('species', models.IntegerField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], verbose_name='Suga')),
                ('status', models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], verbose_name='Statuss')),
                ('pattern', models.IntegerField(blank=True, choices=[(1, 'Vienkrāsains'), (2, 'Strīpains'), (3, 'Punktveida'), (4, 'Plankumains'), (5, 'Raibs')], null=True, verbose_name='Kažoka raksts')),
                ('primary_color', models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Pamatkrāsa')),
                ('secondary_color', models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Sekundārā krāsa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Piezīmes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ziņots')),
                ('contact_phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='Kontakttālrunis')),
                ('phone_code', models.IntegerField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], null=True, verbose_name='Telefona kods')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sķirne')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais garums')),
                ('pet_image_1', models.URLField(max_length=255, verbose_name='Mājdzīvnieka 1. attēls')),
                ('pet_image_2', models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 2. attēls')),
                ('pet_image_3', models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 3. attēls')),
                ('pet_image_4', models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 4. attēls')),
                ('event_occurred_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks')),
                ('is_public', models.BooleanField(default=True, verbose_name='Vai ir publisks?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mājdzīvnieks',
                'verbose_name_plural': 'Mājdzīvnieki',
            },
        ),
        migrations.CreateModel(
            name='PetSightingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Atrasts'), (2, 'Redzēts')], default=2, verbose_name='Statuss')),
                ('event_occurred_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ziņots')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais garums')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Piezīmes')),
                ('pet_image', models.URLField(max_length=255, verbose_name='Mājdzīvnieka attēls')),
                ('is_public', models.BooleanField(default=True, verbose_name='Vai ir publisks?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings_history', to='pets.pet')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ziņotājs')),
            ],
            options={
                'verbose_name': 'Mājdzīvnieka novērojums',
                'verbose_name_plural': 'Mājdzīvnieka novērojumi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'pet'), name='unique_user_pet')],
            },
        ),
    ]
