# Generated by Django 5.1.3 on 2025-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_extra_image_1_alter_pet_extra_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='extra_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_image_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_image_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
