# Generated by Django 5.1.3 on 2024-11-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_author_pet_behavior_pet_gender_pet_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='author',
        ),
    ]
