# Generated by Django 5.1.3 on 2025-03-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_extra_image_1_alter_pet_extra_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='extra_image_1',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='extra_image_2',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='extra_image_3',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='extra_image_4',
        ),
        migrations.RemoveField(
            model_name='petsightinghistory',
            name='image',
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image_url'),
        ),
    ]
