# Generated by Django 5.1.3 on 2024-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='behavior',
            field=models.CharField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], max_length=1, null=True),
        ),
    ]
