# Generated by Django 5.1.3 on 2025-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_extra_image_1_remove_pet_extra_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
