# Generated by Django 5.1.3 on 2024-11-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_species_alter_pet_behavior_alter_pet_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], max_length=1),
        ),
    ]
