# Generated by Django 5.1.3 on 2025-03-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='image',
            new_name='pet_image',
        ),
    ]
