# Generated by Django 5.1.3 on 2025-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_rename_image_pet_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsightinghistory',
            name='pet_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
