# Generated by Django 5.1.3 on 2025-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_petsightinghistory_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=24.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=25.0, max_digits=9),
            preserve_default=False,
        ),
    ]
