# Generated by Django 5.1.3 on 2024-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_behavior_alter_pet_gender_alter_pet_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='behavior',
            field=models.CharField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], max_length=1),
        ),
    ]
