# Generated by Django 5.1.3 on 2025-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_latitude_pet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], default=1, verbose_name='Statuss'),
            preserve_default=False,
        ),
    ]
