# Generated by Django 5.1.3 on 2024-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_behavior_alter_pet_gender_alter_pet_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='behavior',
            field=models.IntegerField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.IntegerField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')]),
        ),
    ]
