# Generated by Django 5.1.3 on 2024-11-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_behavior_alter_pet_gender_alter_pet_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='event_occurred_at',
        ),
        migrations.AlterField(
            model_name='pet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Autors'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='behavior',
            field=models.IntegerField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], null=True, verbose_name='Uzvedība'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], null=True, verbose_name='Dzimums'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifikātors'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], null=True, verbose_name='Izmērs'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.IntegerField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], verbose_name='Suga'),
        ),
        migrations.CreateModel(
            name='PetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], verbose_name='Statuss')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='Notikuma laiks')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pets.pet')),
            ],
        ),
    ]
