# Generated by Django 5.1.3 on 2025-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notikuma laiks'),
        ),
    ]
