# Generated by Django 5.1.3 on 2025-04-03 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_pet_event_occurred_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorites',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userfavorites',
            constraint=models.UniqueConstraint(fields=('user', 'pet'), name='unique_user_pet'),
        ),
    ]
