# Generated by Django 5.1.3 on 2025-04-03 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_userfavorites_created_at_alter_userfavorites_pet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petsightinghistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='petsightinghistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='petsightinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
