# Generated by Django 5.1.3 on 2024-12-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_pet_image_pet_notes_alter_petsightinghistory_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, 'Mazulis'), (2, 'Pieaugušais'), (3, 'Seniors')], null=True, verbose_name='Vecums'),
        ),
        migrations.AddField(
            model_name='pet',
            name='extra_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 1.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='extra_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 2.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='extra_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 3.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='extra_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Papildus attēls 4.'),
        ),
    ]
