# Generated by Django 5.1.3 on 2025-04-03 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_alter_petsightinghistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petsightinghistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mājdzīvnieka novērojums', 'verbose_name_plural': 'Mājdzīvnieka novērojumi'},
        ),
        migrations.AddField(
            model_name='petsightinghistory',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Vai ir publisks?'),
        ),
        migrations.AddField(
            model_name='petsightinghistory',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais platums'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais garums'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ziņots'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais platums'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais garums'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Piezīmes'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='pet_image',
            field=models.CharField(default='nav link', max_length=255, verbose_name='Bildes URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ziņotājs'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Atrasts'), (2, 'Redzēts')], default=2, verbose_name='Statuss'),
        ),
    ]
