# Generated by Django 5.1.3 on 2024-12-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_pet_age_pet_extra_image_1_pet_extra_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsightinghistory',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notikuma laiks'),
        ),
        migrations.AddField(
            model_name='petsightinghistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], default=1, verbose_name='Statuss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
