# Generated by Django 5.1.3 on 2024-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_petsightinghistory_event_occurred_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pattern',
            field=models.IntegerField(blank=True, choices=[(1, 'Vienkrāsains'), (2, 'Strīpains'), (3, 'Punktveida'), (4, 'Plankumains'), (5, 'Raibs')], null=True, verbose_name='Kažoka raksts'),
        ),
    ]
