# Generated by Django 5.1.3 on 2025-04-03 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_alter_petsightinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Vai ir publisks?'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Kontakttālrunis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-01 22:10:00+00', verbose_name='Ziņots'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.CharField(default='test', max_length=255, verbose_name='Mājdzīvnieka attēls'),
            preserve_default=False,
        ),
    ]
