# Generated by Django 5.1.3 on 2025-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_pet_is_public_pet_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontakttālrunis'),
        ),
    ]
