# Generated by Django 5.1.3 on 2024-12-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_pet_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='primary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Pamatkrāsa'),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Sekundārā krāsa'),
        ),
    ]
