# Generated by Django 5.1.3 on 2025-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_alter_pet_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Kontakttālrunis'),
        ),
    ]
