# Generated by Django 5.1.3 on 2024-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_pet_primary_color_pet_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='Kontakttālrunis'),
        ),
    ]
