# Generated by Django 5.1.3 on 2025-04-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_alter_pet_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_image',
            new_name='pet_image_1',
        ),
    ]
