# Generated by Django 5.1.3 on 2025-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_pet_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petsightinghistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='petstatushistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontakttālrunis'),
        ),
    ]
