# Generated by Django 5.1.3 on 2025-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_rename_pet_image_pet_pet_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image_1',
            field=models.URLField(max_length=255, verbose_name='Mājdzīvnieka 1. attēls'),
        ),
    ]
