# Generated by Django 5.1.3 on 2025-01-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_alter_petsightinghistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='Mājdzīvnieki',
        ),
    ]
