# Generated by Django 5.1.3 on 2025-01-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_pet_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Mājdzīvnieks', 'verbose_name_plural': 'Mājdzīvnieki'},
        ),
        migrations.AlterModelTable(
            name='pet',
            table=None,
        ),
    ]
