# Generated by Django 5.1.3 on 2025-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_pet_pet_image_2_pet_pet_image_3_pet_pet_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image_2',
            field=models.URLField(default='https://hello.com', max_length=255, verbose_name='Mājdzīvnieka 2. attēls'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_3',
            field=models.URLField(default='https://hello.com', max_length=255, verbose_name='Mājdzīvnieka 3. attēls'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_4',
            field=models.URLField(default='https://hello.com', max_length=255, verbose_name='Mājdzīvnieka 4. attēls'),
            preserve_default=False,
        ),
    ]
