# Generated by Django 5.1.3 on 2025-01-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_alter_pet_options_alter_pet_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetStatusHistory',
        ),
    ]
