# Generated by Django 5.1.3 on 2025-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_delete_petstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsightinghistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sightnings_images/', verbose_name='Attēls'),
        ),
    ]
