# Generated by Django 5.1.3 on 2025-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_alter_pet_pet_image_2_alter_pet_pet_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image_1',
            field=models.CharField(max_length=255, verbose_name='Mājdzīvnieka 1. attēls'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_2',
            field=models.CharField(max_length=255, verbose_name='Mājdzīvnieka 2. attēls'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_3',
            field=models.CharField(max_length=255, verbose_name='Mājdzīvnieka 3. attēls'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_4',
            field=models.CharField(max_length=255, verbose_name='Mājdzīvnieka 4. attēls'),
        ),
    ]
