# Generated by Django 5.1.3 on 2025-02-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_userfavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='phone_code',
            field=models.IntegerField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], null=True, verbose_name='Telefona kods'),
        ),
    ]
