# Generated by Django 5.1.3 on 2025-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_pet_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sķirne'),
        ),
    ]
