# Generated by Django 5.1.3 on 2025-04-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nosaukums')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Apraksts')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Vietne')),
                ('country', models.CharField(blank=True, choices=[('LV', 'Latvija'), ('EE', 'Igaunija'), ('LT', 'Lietuva')], max_length=2, null=True, verbose_name='Valsts')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reģions')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pilsēta')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Iela')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasta indekss')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='Adrese')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefona numurs')),
                ('phone_code', models.CharField(blank=True, choices=[('+371', 'Latvija (+371)'), ('+370', 'Lietuva (+370)'), ('+372', 'Igaunija (+372)')], max_length=5, null=True, verbose_name='Telefona kods')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-pasts')),
                ('social_media', models.ManyToManyField(blank=True, related_name='shelters', to='core.socialmedia', verbose_name='Sociālie mediji')),
            ],
        ),
    ]
