# Generated by Django 5.1.3 on 2024-12-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='phone_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonecode'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Pilsēta'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Valsts'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Apraksts'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-pasts'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Adrese'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nosaukums'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefona numurs'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasta indekss'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reģions'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Iela'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Vietne'),
        ),
    ]
