# Generated by Django 5.1.3 on 2024-12-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_phone_code_alter_shelter_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='phone_code',
        ),
    ]
