# Generated by Django 5.1.3 on 2024-12-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_country_code_alter_country_currency_and_more'),
        ('shelters', '0005_alter_shelter_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
