# Generated by Django 5.1.3 on 2024-12-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0007_alter_shelter_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='social_media',
        ),
    ]
