# Generated by Django 5.1.3 on 2024-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
        ('shelters', '0008_remove_shelter_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='shelters', to='core.socialmedia', verbose_name='Sociālie mediji'),
        ),
    ]
