# Generated by Django 5.1.3 on 2024-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0009_shelter_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='social_media',
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('+371', 'Latvia (+371)'), ('+370', 'Lithuania (+370)'), ('+372', 'Estonia (+372)')], max_length=5, null=True, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pilsēta'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvia'), ('EE', 'Estonia'), ('LT', 'Lithuania')], max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Iela'),
        ),
    ]
