# Generated by Django 5.1.3 on 2024-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_country'),
        ('shelters', '0010_remove_shelter_social_media_shelter_phone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='shelters', to='core.socialmedia', verbose_name='Sociālie mediji'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvia'), ('EE', 'Estonia'), ('LT', 'Lithuania')], max_length=2, null=True, verbose_name='Valsts'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('+371', 'Latvia (+371)'), ('+370', 'Lithuania (+370)'), ('+372', 'Estonia (+372)')], max_length=5, null=True, verbose_name='Telefona kods'),
        ),
    ]
