# Generated by Django 5.1.3 on 2024-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0011_shelter_social_media_alter_shelter_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvija'), ('EE', 'Igaunija'), ('LT', 'Lietuva')], max_length=2, null=True, verbose_name='Valsts'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('+371', 'Latvija (+371)'), ('+370', 'Lietuva (+370)'), ('+372', 'Igaunija (+372)')], max_length=5, null=True, verbose_name='Telefona kods'),
        ),
    ]
