# Generated by Django 5.1.3 on 2025-04-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvija'), ('EE', 'Igaunija'), ('LT', 'Lietuva')], max_length=2, null=True, verbose_name='Valsts'),
        ),
        migrations.AddField(
            model_name='location',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Adrese'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('+371', 'Latvija (+371)'), ('+370', 'Lietuva (+370)'), ('+372', 'Igaunija (+372)')], max_length=5, null=True, verbose_name='Telefona kods'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasta indekss'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reģions'),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Iela'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this service currently accepting requests?'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='provider_type',
            field=models.IntegerField(choices=[(1, 'Fiziska persona'), (2, 'Juridiska persona')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.URLField(default=22, max_length=255, verbose_name='Servisa attēls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Vietne'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pilsēta'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-pasts'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefona numurs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.IntegerField(choices=[(1, 'Dzīvnieku pieskatīšana'), (2, 'Suņu pastaigas'), (3, 'Kopšana'), (4, 'Apmācība'), (5, 'Izmitināšana'), (6, 'Veterinārārsts'), (7, 'Foto sesijas'), (8, 'Glābšana un meklēšana'), (9, 'Piederumi un aksesuāri'), (10, 'Māksla'), (11, 'Apbedīšana'), (12, 'Transports'), (13, 'Audzētavas'), (14, 'Apdrošināšana'), (15, 'Citi pakalpojumi')]),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.IntegerField(choices=[(0, 'Pirmdiena'), (1, 'Otrdiena'), (2, 'Trešdiena'), (3, 'Ceturtdiena'), (4, 'Piektdiena'), (5, 'Sestdiena'), (6, 'Svētdiena')]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service', 'user')},
            },
        ),
    ]
