# Generated by Django 5.1.3 on 2025-04-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0003_service_email_service_phone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='services', to='core.socialmedia', verbose_name='Sociālie mediji'),
        ),
    ]
