# Generated by Django 5.1.3 on 2025-04-20 15:32

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_social_media'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_description',
            field=models.TextField(default='business description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_title',
            field=models.CharField(default='business description title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
