# Generated by Django 5.1.3 on 2025-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_location_location_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stundā'), (2, 'Vienībā'), (3, 'Dienā'), (4, 'Pēc vienošanās')], default=1, max_length=20),
        ),
    ]
