# Generated by Django 5.1.3 on 2025-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_duration_remove_service_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Stundā'), (2, 'Vienībā'), (3, 'Dienā'), (4, 'Pēc vienošanās')], default=1),
        ),
    ]
