# Generated by Django 5.1.3 on 2025-04-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_userservicefavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
