# Generated by Django 5.1.3 on 2025-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_review_comment_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image_1',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Servisa attēls 1.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image_2',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Servisa attēls 2.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image_3',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Servisa attēls 3.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image_4',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Servisa attēls 4.'),
            preserve_default=False,
        ),
    ]
