# Generated by Django 5.1.3 on 2025-05-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_service_image_1_service_service_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
    ]
