# Generated by Django 5.1.3 on 2025-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Servisa attēls'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkingHour',
        ),
    ]
