# Generated by Django 5.1.3 on 2025-05-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
    ]
