# Generated by Django 5.1.3 on 2025-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image_1',
            field=models.URLField(max_length=255, verbose_name='Servisa 1. attēls'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image_2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 2. attēls'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image_3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 3. attēls'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image_4',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 4. attēls'),
        ),
    ]
