# Generated by Django 5.1.3 on 2025-05-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_service_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.AddField(
            model_name='service',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reģions')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pilsēta')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Iela')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasta indekss')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='Adrese')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='services.service')),
            ],
        ),
    ]
