# Generated by Django 5.1.3 on 2025-05-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_service_tags_service_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone_code',
            field=models.CharField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], max_length=5, null=True, verbose_name='Telefona kods'),
        ),
    ]
