# Generated by Django 5.1.3 on 2025-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_animal',
            field=models.CharField(blank=True, default='cat', max_length=100, null=True),
        ),
    ]
