# Generated by Django 5.1.3 on 2025-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_avatar_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_animal',
            field=models.CharField(blank=True, default='Cat', max_length=100, null=True),
        ),
    ]
