# Generated by Django 5.1.3 on 2025-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='distance',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='lat',
            field=models.FloatField(default=24.44),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='lon',
            field=models.FloatField(default=55.66),
            preserve_default=False,
        ),
    ]
