# Generated by Django 5.1.3 on 2025-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription_distance_pushsubscription_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='lat',
            field=models.FloatField(default=56.946),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='lon',
            field=models.FloatField(default=24.1059),
        ),
    ]
